project_id = "hard-problem"

[auth]
site_url = "https://hardproblem.club"
additional_redirect_urls = ["https://hardproblem.club/**", "https://hardproblem.club/auth/callback", "https://hardproblem.club/auth/callback?*"]
enable_anonymous_sign_ins = true

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8
